name: CI-CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TZ: Asia/Shanghai
  GITEE_REPO_ADDRESS: gitee.com/llnancy/zhenyaojian-pages.git

jobs:
  build:
    name: CI CD
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install And Gulp
        run: |
          npm install yarn -g
          npm install hexo-cli -g
          yarn install
          yarn build

      - name: Deploy
        run: |
          git clone https://llnancy:${{ secrets.GITEE_TOKEN }}@$GITEE_REPO_ADDRESS .deploy_git
          mv .deploy_git/.git/ ./dist/
          cd ./dist
          git config user.name "llnancy"
          git config user.email "admin@lilu.org.cn"
          git add .
          git commit -m "Github Actions Auto Builder at $(date +'%Y-%m-%d %H:%M')"
          git push --force --quiet "https://llnancy:${{ secrets.GITEE_TOKEN }}@$GITEE_REPO_ADDRESS" master:master
